#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# pi-config-sync.sh
# Sync pi agent configuration across devices via a dotfiles repo.
#
# Usage:
#   pi-config-sync.sh init           # init dotfiles repo with current config
#   pi-config-sync.sh push           # push current pi config to dotfiles
#   pi-config-sync.sh pull           # pull pi config from dotfiles to current device
#
# Environment variables:
#   DOTFILES_DIR   Override dotfiles path (default: script's directory)
#   PI_DIR         Override pi agent directory (default: ~/.pi/agent)
# ============================================================================

PI_DIR="${PI_DIR:-$HOME/.pi/agent}"
# 默认 dotfiles 目录为脚本所在目录（即本仓库目录）
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOTFILES_DIR="${DOTFILES_DIR:-$SCRIPT_DIR}"

# Files/dirs to sync (relative to PI_DIR)
# NOTE: settings.json is NOT synced directly — use settings.base.json instead.
#       settings.json is auto-generated by pi-config-merge.sh from base + local.
SYNC_FILES=(
  "settings.base.json"
  "APPEND_SYSTEM.md"
  "skills"
  "extensions"
  "themes"
  "prompts"
)

# Sensitive / auto-generated files to never sync
IGNORE_FILES=(
  "auth.json"
  "sessions"
  "npm"
  "bin"
  "settings.json"
  "settings.local.json"
)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}   $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_err()   { echo -e "${RED}[ERR]${NC}  $*"; }

print_help() {
  cat << 'EOF'
Usage: pi-config-sync.sh <command>

Commands:
  init      Initialize a dotfiles repo with current pi config
  push      Export current pi config to dotfiles repo
  pull      Import pi config from dotfiles repo to current device
  status    Show what would be synced
  help      Show this help message

Environment variables:
  DOTFILES_DIR   Path to dotfiles directory (default: script's directory)
  PI_DIR         Path to pi agent directory (default: ~/.pi/agent)

Examples:
  ./pi-config-sync.sh init
  ./pi-config-sync.sh push
  ./pi-config-sync.sh pull

  # Override paths
  PI_DIR=/custom/.pi/agent ./pi-config-sync.sh push
EOF
}

check_deps() {
  if ! command -v git &> /dev/null; then
    log_err "git is required but not installed."
    exit 1
  fi
}

ensure_pi_dir() {
  if [[ ! -d "$PI_DIR" ]]; then
    log_err "Pi agent directory not found: $PI_DIR"
    log_info "Make sure pi is installed and has been run at least once."
    exit 1
  fi
}

ensure_dotfiles_dir() {
  if [[ ! -d "$DOTFILES_DIR" ]]; then
    mkdir -p "$DOTFILES_DIR"
  fi
}

write_gitignore() {
  local gitignore="$DOTFILES_DIR/.gitignore"
  log_info "Writing $gitignore ..."
  cat > "$gitignore" << 'EOF'
# NEVER sync these — sensitive or auto-generated
auth.json
sessions/
npm/
bin/

# Generated files (use pi-config-merge.sh to regenerate)
settings.json
settings.local.json

# Platform-specific base config is synced, but local overrides stay device-local
EOF
  log_ok "Gitignore written."
}

cmd_init() {
  ensure_pi_dir
  ensure_dotfiles_dir

  log_info "Initializing dotfiles repo at: $DOTFILES_DIR"

  if [[ -d "$DOTFILES_DIR/.git" ]]; then
    log_warn "Git repo already exists at $DOTFILES_DIR"
  else
    (cd "$DOTFILES_DIR" && git init)
    log_ok "Git repo initialized."
  fi

  write_gitignore

  # Copy initial files
  for item in "${SYNC_FILES[@]}"; do
    local src="$PI_DIR/$item"
    local dst="$DOTFILES_DIR/$item"
    if [[ -e "$src" ]]; then
      if [[ -d "$src" ]]; then
        rsync -a --delete "$src/" "$dst/" 2>/dev/null || cp -r "$src" "$dst"
      else
        cp "$src" "$dst"
      fi
      log_ok "Copied: $item"
    else
      log_warn "Skipped (not found): $item"
    fi
  done

  log_info "Dotfiles repo ready at: $DOTFILES_DIR"
  log_info "Next steps:"
  echo "  1. cd $DOTFILES_DIR"
  echo "  2. git remote add origin <your-private-repo-url>"
  echo "  3. git add . && git commit -m 'Initial pi config'"
  echo "  4. git push -u origin main"
}

cmd_push() {
  ensure_pi_dir

  if [[ ! -d "$DOTFILES_DIR/.git" ]]; then
    log_err "No git repo found at $DOTFILES_DIR"
    log_info "Run 'init' first, or ensure DOTFILES_DIR is correct."
    exit 1
  fi

  log_info "Pushing pi config to: $DOTFILES_DIR"

  for item in "${SYNC_FILES[@]}"; do
    local src="$PI_DIR/$item"
    local dst="$DOTFILES_DIR/$item"
    if [[ -e "$src" ]]; then
      if [[ -d "$src" ]]; then
        mkdir -p "$dst"
        rsync -a --delete "$src/" "$dst/" 2>/dev/null || {
          rm -rf "$dst"
          cp -r "$src" "$dst"
        }
      else
        cp "$src" "$dst"
      fi
      log_ok "Synced: $item"
    else
      log_warn "Skipped (not found): $item"
    fi
  done

  (cd "$DOTFILES_DIR" && {
    git add -A
    if git diff --cached --quiet; then
      log_ok "No changes to commit."
    else
      git commit -m "Update pi config ($(date -Iseconds))"
      log_ok "Changes committed."
      log_info "Run 'git push' to sync with remote."
    fi
  })
}

cmd_pull() {
  ensure_pi_dir

  if [[ ! -d "$DOTFILES_DIR" ]]; then
    log_err "Dotfiles directory not found: $DOTFILES_DIR"
    log_info "Clone your dotfiles repo first, or run 'init' to create it."
    exit 1
  fi

  log_info "Pulling pi config from: $DOTFILES_DIR"
  log_warn "This will overwrite your current pi configuration!"
  read -rp "Continue? [y/N] " confirm
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    log_info "Aborted."
    exit 0
  fi

  # Backup current auth.json if exists
  if [[ -f "$PI_DIR/auth.json" ]]; then
    local backup="$PI_DIR/auth.json.bak.$(date +%s)"
    cp "$PI_DIR/auth.json" "$backup"
    log_warn "Backed up auth.json to: $backup"
  fi

  # Backup current settings.json
  if [[ -f "$PI_DIR/settings.json" ]]; then
    cp "$PI_DIR/settings.json" "$PI_DIR/settings.json.bak.$(date +%s)"
  fi

  for item in "${SYNC_FILES[@]}"; do
    local src="$DOTFILES_DIR/$item"
    local dst="$PI_DIR/$item"
    if [[ -e "$src" ]]; then
      if [[ -d "$src" ]]; then
        mkdir -p "$dst"
        rsync -a --delete "$src/" "$dst/" 2>/dev/null || {
          rm -rf "$dst"
          cp -r "$src" "$dst"
        }
      else
        cp "$src" "$dst"
      fi
      log_ok "Restored: $item"
    else
      log_warn "Skipped (not found in dotfiles): $item"
    fi
  done

  log_ok "Configuration restored!"
  echo ""

  # Auto-merge settings if possible
  if [[ -f "$PI_DIR/settings.base.json" ]]; then
    if [[ ! -f "$PI_DIR/settings.local.json" ]]; then
      log_warn "No settings.local.json found — this device needs local overrides."
      log_info "Run: ./pi-config-merge.sh init-local"
    else
      log_info "Auto-merging settings.base.json + settings.local.json ..."
      if command -v jq &> /dev/null; then
        ./pi-config-merge.sh merge 2>/dev/null || {
          log_warn "Auto-merge failed. Run './pi-config-merge.sh merge' manually."
        }
      else
        log_warn "jq not found, cannot auto-merge. Install jq and run './pi-config-merge.sh merge'"
      fi
    fi
  fi

  echo ""
  log_warn "IMPORTANT: settings.json was generated from base + local configs."
  echo "  - If this is a new device, review $PI_DIR/settings.local.json"
  echo "  - Adjust shellPath, shellCommandPrefix, and other platform paths"
  echo ""
  log_info "To regenerate settings.json after edits:"
  echo "  ./pi-config-merge.sh merge"
  echo ""
  log_info "To reinstall packages from settings.json, run:"
  echo "  pi update --extensions"
  echo ""
  log_info "To restore your API keys, re-run 'pi login' or edit auth.json."
}

cmd_status() {
  ensure_pi_dir
  ensure_dotfiles_dir

  echo ""
  echo "=== Pi Agent Directory ==="
  echo "  Source: $PI_DIR"
  echo ""
  echo "=== Dotfiles Directory ==="
  echo "  Target: $DOTFILES_DIR"
  echo ""
  echo "=== Files to Sync ==="
  for item in "${SYNC_FILES[@]}"; do
    local src="$PI_DIR/$item"
    local dst="$DOTFILES_DIR/$item"
    local status=""
    if [[ ! -e "$src" ]]; then
      status="${YELLOW}(not found in pi dir)${NC}"
    elif [[ ! -e "$dst" ]]; then
      status="${CYAN}(not yet in dotfiles)${NC}"
    else
      if diff -rq "$src" "$dst" &>/dev/null; then
        status="${GREEN}✓ in sync${NC}"
      else
        status="${RED}✗ differs${NC}"
      fi
    fi
    printf "  %-20s %s\n" "$item" "$status"
  done
  echo ""
  echo "=== Ignored (never synced) ==="
  for item in "${IGNORE_FILES[@]}"; do
    printf "  %s\n" "$item"
  done
  echo ""
}

# ============================================================================
# Main
# ============================================================================

check_deps

case "${1:-help}" in
  init)
    cmd_init
    ;;
  push)
    cmd_push
    ;;
  pull)
    cmd_pull
    ;;
  status)
    cmd_status
    ;;
  help|--help|-h)
    print_help
    ;;
  *)
    log_err "Unknown command: $1"
    print_help
    exit 1
    ;;
esac
